services:
  - type: web
    name: codementor-api
    runtime: python
    region: oregon
    plan: free

    pythonVersion: 3.12.9

    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: FRONTEND_URL
        value: https://pro-frontend-wine.vercel.app
      - key: CORS_ORIGINS
        value: http://localhost:3000,https://pro-frontend-wine.vercel.app
      - key: ENVIRONMENT
        value: production
      - key: APP_NAME
        value: CodeMentor
      - key: CHAT_RATE_LIMIT_PER_MINUTE
        value: "30"
